In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [15]:
# Importing the dataset
dataset = pd.read_csv('/content/drive/My Drive/Colab Notebooks/predicting-churn-for-bank-customers/Churn_Modelling.csv')
dataset.head()


RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
X = dataset.iloc[:, 3:13]
y = dataset.iloc[:, 13]


In [17]:
X.head()

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [18]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [0]:
# convert categorical feature into dummy variables

states=pd.get_dummies(X['Geography'],drop_first=True)
gender=pd.get_dummies(X['Gender'],drop_first=True)

In [20]:
states

Germany  Spain
0           0      0
1           0      1
2           0      0
3           0      0
4           0      1
...       ...    ...
9995        0      0
9996        0      0
9997        0      0
9998        1      0
9999        0      0

[10000 rows x 2 columns]

In [21]:
gender

Male
0        0
1        0
2        0
3        0
4        0
...    ...
9995     1
9996     1
9997     0
9998     1
9999     0

[10000 rows x 1 columns]

In [22]:
#drop the columns as it is no longer required

X=X.drop(['Geography','Gender'],axis=1)
X

CreditScore  Age  Tenure  ...  HasCrCard  IsActiveMember  EstimatedSalary
0             619   42       2  ...          1               1        101348.88
1             608   41       1  ...          0               1        112542.58
2             502   42       8  ...          1               0        113931.57
3             699   39       1  ...          0               0         93826.63
4             850   43       2  ...          1               1         79084.10
...           ...  ...     ...  ...        ...             ...              ...
9995          771   39       5  ...          1               0         96270.64
9996          516   35      10  ...          1               1        101699.77
9997          709   36       7  ...          0               1         42085.58
9998          772   42       3  ...          1               0         92888.52
9999          792   28       4  ...          1               0         38190.78

[10000 rows x 8 columns]

In [23]:
#concatenate the remaining dummies columns
X=pd.concat([X,states,gender],axis=1)
X

CreditScore  Age  Tenure  ...  Germany  Spain  Male
0             619   42       2  ...        0      0     0
1             608   41       1  ...        0      1     0
2             502   42       8  ...        0      0     0
3             699   39       1  ...        0      0     0
4             850   43       2  ...        0      1     0
...           ...  ...     ...  ...      ...    ...   ...
9995          771   39       5  ...        0      0     1
9996          516   35      10  ...        0      0     1
9997          709   36       7  ...        0      0     0
9998          772   42       3  ...        1      0     1
9999          792   28       4  ...        0      0     0

[10000 rows x 11 columns]

In [0]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [0]:
# Feature Scaling = standard normal distribution where mean is 0 SD is 1
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [29]:
X_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [30]:
X_test

array([[-0.55204276, -0.36890377,  1.04473698, ...,  1.75486502,
        -0.57369368, -1.09168714],
       [-1.31490297,  0.10961719, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ..., -0.5698444 ,
         1.74309049,  0.91601335],
       [-0.00566991, -0.46460796, -0.33936434, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-0.79945688, -0.84742473,  1.04473698, ...,  1.75486502,
        -0.57369368,  0.91601335]])

In [0]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras  # in keras we see the model structure very clearly
from keras.models import Sequential  # create the neural n/w
from keras.layers import Dense  # creates the hidden layers and neurons present in the hidden layers

In [32]:
# Initialising the ANN
classifier = Sequential()

In [33]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform"))
# 11 features and 6 neurons 
# kernel_initializer = uniform (weights are initialized randomly between 0 to 1)

In [0]:
# Adding the second hidden layer
classifier.add(Dense(activation="relu", units=6, kernel_initializer="uniform"))

In [0]:
# Adding the output layer
classifier.add(Dense(activation="sigmoid", units=1, kernel_initializer="uniform"))

In [39]:
classifier.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 6)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_3 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 7         
Total params: 163
Trainable params: 163
Non-trainable params: 0
_________________________________________________________________


In [37]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
# binary_crossentropy = only 2 o/p
# categorical_crossentropy = more than 2 o/p's



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [38]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.





Epoch 1/100





8000/8000 [==============================] - 9s 1ms/step - loss: 0.4823 - acc: 0.7961
Epoch 2/100
8000/8000 [==============================] - 4s 485us/step - loss: 0.4302 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 4s 476us/step - loss: 0.4243 - acc: 0.7986
Epoch 4/100
8000/8000 [==============================] - 4s 484us/step - loss: 0.4204 - acc: 0.8202
Epoch 5/100
8000/8000 [==============================] - 4s 491us/step - loss: 0.4177 - acc: 0.8237
Epoch 6/100
8000/8000 [==============================] - 4s 486us/step - loss: 0.4153 - acc: 0.8255
Epoch 7/100
8000/8000 [==============================] - 4s 483us/step - loss: 0.4143 - acc: 0.8305
Epoch 8/100
8000/8000 [==============================] - 4s 495us/step - loss: 0.4124 - acc: 0.8317
Epoch 9/100
8000/8000 [==============================] - 4s 490us/step - loss: 0.4112 - acc: 0.8319
Epoch 10/100
8000/8000 [==============================] - 4s 471us/step - loss: 0.4102 - acc: 

In [40]:

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred


array([[0.26097584],
       [0.37993178],
       [0.19974974],
       ...,
       [0.23410273],
       [0.17569077],
       [0.1565637 ]], dtype=float32)

In [41]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [0]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
accuracy=accuracy_score(y_test,y_pred)

In [43]:
cm

array([[1531,   64],
       [ 244,  161]])

In [44]:
accuracy

0.846